modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="moddedstrongholds"
version="1.0.0"
displayName="Modded Strongholds"
logoFile="logo.png"
credits="Made by Rellit (Rellit_219)"
authors="Rellit (Rellit_219)"
description='''This mod replaces Minecraft's ancient strongholds with a newer varient.'''

[[dependencies.moddedstrongholds]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.moddedstrongholds]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
